.PHONY:

run_api_gateway:
	go run api_gateway_service/cmd/main.go -config=./api_gateway_service/config/config.yaml

run_writer_microservice:
	go run writer_service/cmd/main.go -config=./writer_service/config/config.yaml

run_reader_microservice:
	go run reader_service/cmd/main.go -config=./reader_service/config/config.yaml

# ==============================================================================
# Docker

docker_dev:
	@echo Starting local docker dev compose
	docker compose -f docker-compose.yaml up -d --build

local:
	@echo Starting local docker compose
	docker compose -f docker-compose.local.yaml up -d --build


# ==============================================================================
# Docker support

FILES := $(shell docker ps -aq)

down-local:
	docker stop $(FILES)
	docker rm $(FILES)

clean:
	docker system prune -f

logs-local:
	docker logs -f $(FILES)


# ==============================================================================
# Modules support

tidy:
	go mod tidy

deps-reset:
	git checkout -- go.mod
	go mod tidy

deps-upgrade:
	go get -u -t -d -v ./...
	go mod tidy

deps-cleancache:
	go clean -modcache


# ==============================================================================
# Linters https://golangci-lint.run/usage/install/

run-linter:
	@echo Starting linters
	golangci-lint run ./...

# ==============================================================================
# PPROF

pprof_heap:
	go tool pprof -http :8006 http://localhost:6060/debug/pprof/heap?seconds=10

pprof_cpu:
	go tool pprof -http :8006 http://localhost:6060/debug/pprof/profile?seconds=10

pprof_allocs:
	go tool pprof -http :8006 http://localhost:6060/debug/pprof/allocs?seconds=10



# ==============================================================================
# Go migrate postgresql https://github.com/golang-migrate/migrate

#DB_NAME = slave_db
DB_NAME = master_db
DB_HOST = localhost
DB_PORT = 5432
SSL_MODE = disable

force_db:
	migrate -database postgres://postgres:postgres@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(SSL_MODE) -path migrations force 1

version_db:
	migrate -database postgres://postgres:postgres@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(SSL_MODE) -path migrations version

migrate_up:
	migrate -database postgres://postgres:postgres@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(SSL_MODE) -path migrations up 1

migrate_down:
	migrate -database postgres://postgres:postgres@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(SSL_MODE) -path migrations down 1


# Generate migrate file
MIGRATE_FILE: init_resource

generate_migrate_file:
	migrate create -ext sql -dir core/migrations/ -seq $(MIGRATE_FILE)

# ==============================================================================
# MongoDB

mongo:
	cd ./migrations/mongo && mongosh admin -u admin -p admin < init.js


# ==============================================================================
# Swagger

swagger:
	@echo Starting swagger generating
	swag init -g **/**/*.go

# ==============================================================================
# Proto

proto_kafka:
	@echo Generating kafka proto
	cd core/proto/kafka && protoc --go_out=. --go-grpc_opt=require_unimplemented_servers=false --go-grpc_out=. kafka.proto

proto_writer:
	@echo Generating product writer microservice proto
	cd core/proto/services/writer/proto_file && protoc --go_out=../proto_buf --go-grpc_opt=require_unimplemented_servers=false --go-grpc_out=../proto_buf product_writer.proto

proto_writer_message:
	@echo Generating product writer messages microservice proto
	cd core/proto/services/writer/proto_file && protoc --go_out=../proto_buf --go-grpc_opt=require_unimplemented_servers=false --go-grpc_out=../proto_buf product_writer_messages.proto

proto_reader:
	@echo Generating product reader microservice proto
	cd core/proto/services/reader/proto_file && protoc --go_out=../proto_buf --go-grpc_opt=require_unimplemented_servers=false --go-grpc_out=../proto_buf product_reader.proto

proto_reader_message:
	@echo Generating product reader messages microservice proto
	cd core/proto/services/reader/proto_file && protoc --go_out=../proto_buf --go-grpc_opt=require_unimplemented_servers=false --go-grpc_out=../proto_buf product_reader_messages.proto