// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TblCommentsColumns holds the columns for the "tbl_comments" table.
	TblCommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "comment", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "user_name", Type: field.TypeString, Size: 100},
		{Name: "avatar", Type: field.TypeString, Default: ""},
		{Name: "time_point", Type: field.TypeFloat64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "video_id", Type: field.TypeUint},
	}
	// TblCommentsTable holds the schema information for the "tbl_comments" table.
	TblCommentsTable = &schema.Table{
		Name:       "tbl_comments",
		Columns:    TblCommentsColumns,
		PrimaryKey: []*schema.Column{TblCommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tbl_comments_tbl_videos_tbl_comments",
				Columns:    []*schema.Column{TblCommentsColumns[9]},
				RefColumns: []*schema.Column{TblVideosColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TblObjectsColumns holds the columns for the "tbl_objects" table.
	TblObjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "coordinate_x", Type: field.TypeInt},
		{Name: "coordinate_y", Type: field.TypeInt},
		{Name: "length", Type: field.TypeInt},
		{Name: "width", Type: field.TypeInt},
		{Name: "order", Type: field.TypeInt},
		{Name: "time_start", Type: field.TypeFloat64},
		{Name: "time_end", Type: field.TypeFloat64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "touch_vector", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "marker_name", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "time_point", Type: field.TypeFloat64, Default: 0},
		{Name: "video_id", Type: field.TypeUint},
	}
	// TblObjectsTable holds the schema information for the "tbl_objects" table.
	TblObjectsTable = &schema.Table{
		Name:       "tbl_objects",
		Columns:    TblObjectsColumns,
		PrimaryKey: []*schema.Column{TblObjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tbl_objects_tbl_videos_tbl_objects",
				Columns:    []*schema.Column{TblObjectsColumns[15]},
				RefColumns: []*schema.Column{TblVideosColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TblReactionsColumns holds the columns for the "tbl_reactions" table.
	TblReactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "number", Type: field.TypeInt},
		{Name: "time_point", Type: field.TypeFloat64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "video_id", Type: field.TypeUint},
	}
	// TblReactionsTable holds the schema information for the "tbl_reactions" table.
	TblReactionsTable = &schema.Table{
		Name:       "tbl_reactions",
		Columns:    TblReactionsColumns,
		PrimaryKey: []*schema.Column{TblReactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tbl_reactions_tbl_videos_tbl_reactions",
				Columns:    []*schema.Column{TblReactionsColumns[8]},
				RefColumns: []*schema.Column{TblVideosColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TblVideosColumns holds the columns for the "tbl_videos" table.
	TblVideosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "video_url", Type: field.TypeString},
		{Name: "config", Type: field.TypeString, Size: 2147483647},
		{Name: "path_resource", Type: field.TypeString, Size: 2147483647},
		{Name: "level_system", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "note", Type: field.TypeString, Size: 2147483647},
		{Name: "assign", Type: field.TypeString},
		{Name: "version", Type: field.TypeUint, Default: 1},
		{Name: "author", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// TblVideosTable holds the schema information for the "tbl_videos" table.
	TblVideosTable = &schema.Table{
		Name:       "tbl_videos",
		Columns:    TblVideosColumns,
		PrimaryKey: []*schema.Column{TblVideosColumns[0]},
	}
	// TblViewersColumns holds the columns for the "tbl_viewers" table.
	TblViewersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "number", Type: field.TypeInt},
		{Name: "time_point", Type: field.TypeFloat64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "video_id", Type: field.TypeUint},
	}
	// TblViewersTable holds the schema information for the "tbl_viewers" table.
	TblViewersTable = &schema.Table{
		Name:       "tbl_viewers",
		Columns:    TblViewersColumns,
		PrimaryKey: []*schema.Column{TblViewersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tbl_viewers_tbl_videos_tbl_viewers",
				Columns:    []*schema.Column{TblViewersColumns[6]},
				RefColumns: []*schema.Column{TblVideosColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TblCommentsTable,
		TblObjectsTable,
		TblReactionsTable,
		TblVideosTable,
		TblViewersTable,
	}
)

func init() {
	TblCommentsTable.ForeignKeys[0].RefTable = TblVideosTable
	TblCommentsTable.Annotation = &entsql.Annotation{
		Table: "tbl_comments",
	}
	TblObjectsTable.ForeignKeys[0].RefTable = TblVideosTable
	TblObjectsTable.Annotation = &entsql.Annotation{
		Table: "tbl_objects",
	}
	TblReactionsTable.ForeignKeys[0].RefTable = TblVideosTable
	TblReactionsTable.Annotation = &entsql.Annotation{
		Table: "tbl_reactions",
	}
	TblVideosTable.Annotation = &entsql.Annotation{
		Table: "tbl_videos",
	}
	TblViewersTable.ForeignKeys[0].RefTable = TblVideosTable
	TblViewersTable.Annotation = &entsql.Annotation{
		Table: "tbl_viewers",
	}
}
