// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/glu/video-real-time-ranking/ent/comments"
	"github.com/glu/video-real-time-ranking/ent/videos"
)

// CommentsCreate is the builder for creating a Comments entity.
type CommentsCreate struct {
	config
	mutation *CommentsMutation
	hooks    []Hook
}

// SetVideoID sets the "video_id" field.
func (cc *CommentsCreate) SetVideoID(u uint) *CommentsCreate {
	cc.mutation.SetVideoID(u)
	return cc
}

// SetDescription sets the "description" field.
func (cc *CommentsCreate) SetDescription(s string) *CommentsCreate {
	cc.mutation.SetDescription(s)
	return cc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (cc *CommentsCreate) SetNillableDescription(s *string) *CommentsCreate {
	if s != nil {
		cc.SetDescription(*s)
	}
	return cc
}

// SetComment sets the "comment" field.
func (cc *CommentsCreate) SetComment(s string) *CommentsCreate {
	cc.mutation.SetComment(s)
	return cc
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (cc *CommentsCreate) SetNillableComment(s *string) *CommentsCreate {
	if s != nil {
		cc.SetComment(*s)
	}
	return cc
}

// SetUserName sets the "user_name" field.
func (cc *CommentsCreate) SetUserName(s string) *CommentsCreate {
	cc.mutation.SetUserName(s)
	return cc
}

// SetAvatar sets the "avatar" field.
func (cc *CommentsCreate) SetAvatar(s string) *CommentsCreate {
	cc.mutation.SetAvatar(s)
	return cc
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (cc *CommentsCreate) SetNillableAvatar(s *string) *CommentsCreate {
	if s != nil {
		cc.SetAvatar(*s)
	}
	return cc
}

// SetTimePoint sets the "time_point" field.
func (cc *CommentsCreate) SetTimePoint(f float64) *CommentsCreate {
	cc.mutation.SetTimePoint(f)
	return cc
}

// SetCreatedAt sets the "created_at" field.
func (cc *CommentsCreate) SetCreatedAt(t time.Time) *CommentsCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CommentsCreate) SetNillableCreatedAt(t *time.Time) *CommentsCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *CommentsCreate) SetUpdatedAt(t time.Time) *CommentsCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *CommentsCreate) SetNillableUpdatedAt(t *time.Time) *CommentsCreate {
	if t != nil {
		cc.SetUpdatedAt(*t)
	}
	return cc
}

// SetDeletedAt sets the "deleted_at" field.
func (cc *CommentsCreate) SetDeletedAt(t time.Time) *CommentsCreate {
	cc.mutation.SetDeletedAt(t)
	return cc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (cc *CommentsCreate) SetNillableDeletedAt(t *time.Time) *CommentsCreate {
	if t != nil {
		cc.SetDeletedAt(*t)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CommentsCreate) SetID(u uint) *CommentsCreate {
	cc.mutation.SetID(u)
	return cc
}

// SetTblVideosID sets the "tbl_videos" edge to the Videos entity by ID.
func (cc *CommentsCreate) SetTblVideosID(id uint) *CommentsCreate {
	cc.mutation.SetTblVideosID(id)
	return cc
}

// SetTblVideos sets the "tbl_videos" edge to the Videos entity.
func (cc *CommentsCreate) SetTblVideos(v *Videos) *CommentsCreate {
	return cc.SetTblVideosID(v.ID)
}

// Mutation returns the CommentsMutation object of the builder.
func (cc *CommentsCreate) Mutation() *CommentsMutation {
	return cc.mutation
}

// Save creates the Comments in the database.
func (cc *CommentsCreate) Save(ctx context.Context) (*Comments, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CommentsCreate) SaveX(ctx context.Context) *Comments {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CommentsCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CommentsCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CommentsCreate) defaults() {
	if _, ok := cc.mutation.Description(); !ok {
		v := comments.DefaultDescription
		cc.mutation.SetDescription(v)
	}
	if _, ok := cc.mutation.Comment(); !ok {
		v := comments.DefaultComment
		cc.mutation.SetComment(v)
	}
	if _, ok := cc.mutation.Avatar(); !ok {
		v := comments.DefaultAvatar
		cc.mutation.SetAvatar(v)
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := comments.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		v := comments.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CommentsCreate) check() error {
	if _, ok := cc.mutation.VideoID(); !ok {
		return &ValidationError{Name: "video_id", err: errors.New(`ent: missing required field "Comments.video_id"`)}
	}
	if v, ok := cc.mutation.VideoID(); ok {
		if err := comments.VideoIDValidator(v); err != nil {
			return &ValidationError{Name: "video_id", err: fmt.Errorf(`ent: validator failed for field "Comments.video_id": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Comment(); !ok {
		return &ValidationError{Name: "comment", err: errors.New(`ent: missing required field "Comments.comment"`)}
	}
	if v, ok := cc.mutation.Comment(); ok {
		if err := comments.CommentValidator(v); err != nil {
			return &ValidationError{Name: "comment", err: fmt.Errorf(`ent: validator failed for field "Comments.comment": %w`, err)}
		}
	}
	if _, ok := cc.mutation.UserName(); !ok {
		return &ValidationError{Name: "user_name", err: errors.New(`ent: missing required field "Comments.user_name"`)}
	}
	if v, ok := cc.mutation.UserName(); ok {
		if err := comments.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "Comments.user_name": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Avatar(); !ok {
		return &ValidationError{Name: "avatar", err: errors.New(`ent: missing required field "Comments.avatar"`)}
	}
	if v, ok := cc.mutation.Avatar(); ok {
		if err := comments.AvatarValidator(v); err != nil {
			return &ValidationError{Name: "avatar", err: fmt.Errorf(`ent: validator failed for field "Comments.avatar": %w`, err)}
		}
	}
	if _, ok := cc.mutation.TimePoint(); !ok {
		return &ValidationError{Name: "time_point", err: errors.New(`ent: missing required field "Comments.time_point"`)}
	}
	if v, ok := cc.mutation.TimePoint(); ok {
		if err := comments.TimePointValidator(v); err != nil {
			return &ValidationError{Name: "time_point", err: fmt.Errorf(`ent: validator failed for field "Comments.time_point": %w`, err)}
		}
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Comments.created_at"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Comments.updated_at"`)}
	}
	if v, ok := cc.mutation.ID(); ok {
		if err := comments.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Comments.id": %w`, err)}
		}
	}
	if _, ok := cc.mutation.TblVideosID(); !ok {
		return &ValidationError{Name: "tbl_videos", err: errors.New(`ent: missing required edge "Comments.tbl_videos"`)}
	}
	return nil
}

func (cc *CommentsCreate) sqlSave(ctx context.Context) (*Comments, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CommentsCreate) createSpec() (*Comments, *sqlgraph.CreateSpec) {
	var (
		_node = &Comments{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(comments.Table, sqlgraph.NewFieldSpec(comments.FieldID, field.TypeUint))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.Description(); ok {
		_spec.SetField(comments.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := cc.mutation.Comment(); ok {
		_spec.SetField(comments.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := cc.mutation.UserName(); ok {
		_spec.SetField(comments.FieldUserName, field.TypeString, value)
		_node.UserName = value
	}
	if value, ok := cc.mutation.Avatar(); ok {
		_spec.SetField(comments.FieldAvatar, field.TypeString, value)
		_node.Avatar = value
	}
	if value, ok := cc.mutation.TimePoint(); ok {
		_spec.SetField(comments.FieldTimePoint, field.TypeFloat64, value)
		_node.TimePoint = value
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(comments.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(comments.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cc.mutation.DeletedAt(); ok {
		_spec.SetField(comments.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := cc.mutation.TblVideosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comments.TblVideosTable,
			Columns: []string{comments.TblVideosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videos.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VideoID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CommentsCreateBulk is the builder for creating many Comments entities in bulk.
type CommentsCreateBulk struct {
	config
	err      error
	builders []*CommentsCreate
}

// Save creates the Comments entities in the database.
func (ccb *CommentsCreateBulk) Save(ctx context.Context) ([]*Comments, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Comments, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommentsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CommentsCreateBulk) SaveX(ctx context.Context) []*Comments {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CommentsCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CommentsCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
