// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/glu/video-real-time-ranking/ent/predicate"
	"github.com/glu/video-real-time-ranking/ent/reactions"
	"github.com/glu/video-real-time-ranking/ent/videos"
)

// ReactionsQuery is the builder for querying Reactions entities.
type ReactionsQuery struct {
	config
	ctx           *QueryContext
	order         []reactions.OrderOption
	inters        []Interceptor
	predicates    []predicate.Reactions
	withTblVideos *VideosQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReactionsQuery builder.
func (rq *ReactionsQuery) Where(ps ...predicate.Reactions) *ReactionsQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *ReactionsQuery) Limit(limit int) *ReactionsQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *ReactionsQuery) Offset(offset int) *ReactionsQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *ReactionsQuery) Unique(unique bool) *ReactionsQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *ReactionsQuery) Order(o ...reactions.OrderOption) *ReactionsQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryTblVideos chains the current query on the "tbl_videos" edge.
func (rq *ReactionsQuery) QueryTblVideos() *VideosQuery {
	query := (&VideosClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(reactions.Table, reactions.FieldID, selector),
			sqlgraph.To(videos.Table, videos.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, reactions.TblVideosTable, reactions.TblVideosColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Reactions entity from the query.
// Returns a *NotFoundError when no Reactions was found.
func (rq *ReactionsQuery) First(ctx context.Context) (*Reactions, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{reactions.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *ReactionsQuery) FirstX(ctx context.Context) *Reactions {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Reactions ID from the query.
// Returns a *NotFoundError when no Reactions ID was found.
func (rq *ReactionsQuery) FirstID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{reactions.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *ReactionsQuery) FirstIDX(ctx context.Context) uint {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Reactions entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Reactions entity is found.
// Returns a *NotFoundError when no Reactions entities are found.
func (rq *ReactionsQuery) Only(ctx context.Context) (*Reactions, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{reactions.Label}
	default:
		return nil, &NotSingularError{reactions.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *ReactionsQuery) OnlyX(ctx context.Context) *Reactions {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Reactions ID in the query.
// Returns a *NotSingularError when more than one Reactions ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *ReactionsQuery) OnlyID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{reactions.Label}
	default:
		err = &NotSingularError{reactions.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *ReactionsQuery) OnlyIDX(ctx context.Context) uint {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReactionsSlice.
func (rq *ReactionsQuery) All(ctx context.Context) ([]*Reactions, error) {
	ctx = setContextOp(ctx, rq.ctx, "All")
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Reactions, *ReactionsQuery]()
	return withInterceptors[[]*Reactions](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *ReactionsQuery) AllX(ctx context.Context) []*Reactions {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Reactions IDs.
func (rq *ReactionsQuery) IDs(ctx context.Context) (ids []uint, err error) {
	if rq.ctx.Unique == nil && rq.path != nil {
		rq.Unique(true)
	}
	ctx = setContextOp(ctx, rq.ctx, "IDs")
	if err = rq.Select(reactions.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *ReactionsQuery) IDsX(ctx context.Context) []uint {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *ReactionsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, "Count")
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*ReactionsQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *ReactionsQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *ReactionsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, "Exist")
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *ReactionsQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReactionsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *ReactionsQuery) Clone() *ReactionsQuery {
	if rq == nil {
		return nil
	}
	return &ReactionsQuery{
		config:        rq.config,
		ctx:           rq.ctx.Clone(),
		order:         append([]reactions.OrderOption{}, rq.order...),
		inters:        append([]Interceptor{}, rq.inters...),
		predicates:    append([]predicate.Reactions{}, rq.predicates...),
		withTblVideos: rq.withTblVideos.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithTblVideos tells the query-builder to eager-load the nodes that are connected to
// the "tbl_videos" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ReactionsQuery) WithTblVideos(opts ...func(*VideosQuery)) *ReactionsQuery {
	query := (&VideosClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withTblVideos = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		VideoID uint `json:"video_id" bson:"video_id"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Reactions.Query().
//		GroupBy(reactions.FieldVideoID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *ReactionsQuery) GroupBy(field string, fields ...string) *ReactionsGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReactionsGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = reactions.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		VideoID uint `json:"video_id" bson:"video_id"`
//	}
//
//	client.Reactions.Query().
//		Select(reactions.FieldVideoID).
//		Scan(ctx, &v)
func (rq *ReactionsQuery) Select(fields ...string) *ReactionsSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &ReactionsSelect{ReactionsQuery: rq}
	sbuild.label = reactions.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReactionsSelect configured with the given aggregations.
func (rq *ReactionsQuery) Aggregate(fns ...AggregateFunc) *ReactionsSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *ReactionsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !reactions.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *ReactionsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Reactions, error) {
	var (
		nodes       = []*Reactions{}
		_spec       = rq.querySpec()
		loadedTypes = [1]bool{
			rq.withTblVideos != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Reactions).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Reactions{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withTblVideos; query != nil {
		if err := rq.loadTblVideos(ctx, query, nodes, nil,
			func(n *Reactions, e *Videos) { n.Edges.TblVideos = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *ReactionsQuery) loadTblVideos(ctx context.Context, query *VideosQuery, nodes []*Reactions, init func(*Reactions), assign func(*Reactions, *Videos)) error {
	ids := make([]uint, 0, len(nodes))
	nodeids := make(map[uint][]*Reactions)
	for i := range nodes {
		fk := nodes[i].VideoID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(videos.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "video_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rq *ReactionsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *ReactionsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(reactions.Table, reactions.Columns, sqlgraph.NewFieldSpec(reactions.FieldID, field.TypeUint))
	_spec.From = rq.sql
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rq.path != nil {
		_spec.Unique = true
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reactions.FieldID)
		for i := range fields {
			if fields[i] != reactions.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if rq.withTblVideos != nil {
			_spec.Node.AddColumnOnce(reactions.FieldVideoID)
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *ReactionsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(reactions.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = reactions.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReactionsGroupBy is the group-by builder for Reactions entities.
type ReactionsGroupBy struct {
	selector
	build *ReactionsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *ReactionsGroupBy) Aggregate(fns ...AggregateFunc) *ReactionsGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *ReactionsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, "GroupBy")
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReactionsQuery, *ReactionsGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *ReactionsGroupBy) sqlScan(ctx context.Context, root *ReactionsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReactionsSelect is the builder for selecting fields of Reactions entities.
type ReactionsSelect struct {
	*ReactionsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *ReactionsSelect) Aggregate(fns ...AggregateFunc) *ReactionsSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *ReactionsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, "Select")
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReactionsQuery, *ReactionsSelect](ctx, rs.ReactionsQuery, rs, rs.inters, v)
}

func (rs *ReactionsSelect) sqlScan(ctx context.Context, root *ReactionsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
