// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/glu/video-real-time-ranking/ent/reactions"
	"github.com/glu/video-real-time-ranking/ent/videos"
)

// Reactions is the model entity for the Reactions schema.
type Reactions struct {
	config `bson:"-" json:"-"`
	// ID of the ent.
	ID uint `json:"id" bson:"_id,omitempty"`
	// VideoID holds the value of the "video_id" field.
	VideoID uint `json:"video_id" bson:"video_id"`
	// Description holds the value of the "description" field.
	Description string `json:"description" bson:"description"`
	// Name holds the value of the "name" field.
	Name string `json:"name" bson:"name"`
	// Number holds the value of the "number" field.
	Number int `json:"number" bson:"number"`
	// TimePoint holds the value of the "time_point" field.
	TimePoint float64 `json:"time_point" bson:"time_point"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at" bson:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at" bson:"deleted_at"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReactionsQuery when eager-loading is set.
	Edges        ReactionsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReactionsEdges holds the relations/edges for other nodes in the graph.
type ReactionsEdges struct {
	// TblVideos holds the value of the tbl_videos edge.
	TblVideos *Videos `json:"tbl_videos,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TblVideosOrErr returns the TblVideos value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReactionsEdges) TblVideosOrErr() (*Videos, error) {
	if e.TblVideos != nil {
		return e.TblVideos, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: videos.Label}
	}
	return nil, &NotLoadedError{edge: "tbl_videos"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Reactions) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reactions.FieldTimePoint:
			values[i] = new(sql.NullFloat64)
		case reactions.FieldID, reactions.FieldVideoID, reactions.FieldNumber:
			values[i] = new(sql.NullInt64)
		case reactions.FieldDescription, reactions.FieldName:
			values[i] = new(sql.NullString)
		case reactions.FieldCreatedAt, reactions.FieldUpdatedAt, reactions.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Reactions fields.
func (r *Reactions) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reactions.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = uint(value.Int64)
		case reactions.FieldVideoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field video_id", values[i])
			} else if value.Valid {
				r.VideoID = uint(value.Int64)
			}
		case reactions.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				r.Description = value.String
			}
		case reactions.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				r.Name = value.String
			}
		case reactions.FieldNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				r.Number = int(value.Int64)
			}
		case reactions.FieldTimePoint:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field time_point", values[i])
			} else if value.Valid {
				r.TimePoint = value.Float64
			}
		case reactions.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				r.CreatedAt = value.Time
			}
		case reactions.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				r.UpdatedAt = value.Time
			}
		case reactions.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				r.DeletedAt = new(time.Time)
				*r.DeletedAt = value.Time
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Reactions.
// This includes values selected through modifiers, order, etc.
func (r *Reactions) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// QueryTblVideos queries the "tbl_videos" edge of the Reactions entity.
func (r *Reactions) QueryTblVideos() *VideosQuery {
	return NewReactionsClient(r.config).QueryTblVideos(r)
}

// Update returns a builder for updating this Reactions.
// Note that you need to call Reactions.Unwrap() before calling this method if this Reactions
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Reactions) Update() *ReactionsUpdateOne {
	return NewReactionsClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Reactions entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Reactions) Unwrap() *Reactions {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Reactions is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Reactions) String() string {
	var builder strings.Builder
	builder.WriteString("Reactions(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("video_id=")
	builder.WriteString(fmt.Sprintf("%v", r.VideoID))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(r.Description)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(r.Name)
	builder.WriteString(", ")
	builder.WriteString("number=")
	builder.WriteString(fmt.Sprintf("%v", r.Number))
	builder.WriteString(", ")
	builder.WriteString("time_point=")
	builder.WriteString(fmt.Sprintf("%v", r.TimePoint))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(r.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(r.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := r.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ReactionsSlice is a parsable slice of Reactions.
type ReactionsSlice []*Reactions
