// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/glu/video-real-time-ranking/ent/comments"
	"github.com/glu/video-real-time-ranking/ent/objects"
	"github.com/glu/video-real-time-ranking/ent/reactions"
	"github.com/glu/video-real-time-ranking/ent/schema"
	"github.com/glu/video-real-time-ranking/ent/videos"
	"github.com/glu/video-real-time-ranking/ent/viewers"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentsFields := schema.Comments{}.Fields()
	_ = commentsFields
	// commentsDescVideoID is the schema descriptor for video_id field.
	commentsDescVideoID := commentsFields[1].Descriptor()
	// comments.VideoIDValidator is a validator for the "video_id" field. It is called by the builders before save.
	comments.VideoIDValidator = commentsDescVideoID.Validators[0].(func(uint) error)
	// commentsDescDescription is the schema descriptor for description field.
	commentsDescDescription := commentsFields[2].Descriptor()
	// comments.DefaultDescription holds the default value on creation for the description field.
	comments.DefaultDescription = commentsDescDescription.Default.(string)
	// commentsDescComment is the schema descriptor for comment field.
	commentsDescComment := commentsFields[3].Descriptor()
	// comments.DefaultComment holds the default value on creation for the comment field.
	comments.DefaultComment = commentsDescComment.Default.(string)
	// comments.CommentValidator is a validator for the "comment" field. It is called by the builders before save.
	comments.CommentValidator = commentsDescComment.Validators[0].(func(string) error)
	// commentsDescUserName is the schema descriptor for user_name field.
	commentsDescUserName := commentsFields[4].Descriptor()
	// comments.UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	comments.UserNameValidator = func() func(string) error {
		validators := commentsDescUserName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(user_name string) error {
			for _, fn := range fns {
				if err := fn(user_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// commentsDescAvatar is the schema descriptor for avatar field.
	commentsDescAvatar := commentsFields[5].Descriptor()
	// comments.DefaultAvatar holds the default value on creation for the avatar field.
	comments.DefaultAvatar = commentsDescAvatar.Default.(string)
	// comments.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	comments.AvatarValidator = commentsDescAvatar.Validators[0].(func(string) error)
	// commentsDescTimePoint is the schema descriptor for time_point field.
	commentsDescTimePoint := commentsFields[6].Descriptor()
	// comments.TimePointValidator is a validator for the "time_point" field. It is called by the builders before save.
	comments.TimePointValidator = commentsDescTimePoint.Validators[0].(func(float64) error)
	// commentsDescCreatedAt is the schema descriptor for created_at field.
	commentsDescCreatedAt := commentsFields[7].Descriptor()
	// comments.DefaultCreatedAt holds the default value on creation for the created_at field.
	comments.DefaultCreatedAt = commentsDescCreatedAt.Default.(func() time.Time)
	// commentsDescUpdatedAt is the schema descriptor for updated_at field.
	commentsDescUpdatedAt := commentsFields[8].Descriptor()
	// comments.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comments.DefaultUpdatedAt = commentsDescUpdatedAt.Default.(func() time.Time)
	// comments.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comments.UpdateDefaultUpdatedAt = commentsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// commentsDescID is the schema descriptor for id field.
	commentsDescID := commentsFields[0].Descriptor()
	// comments.IDValidator is a validator for the "id" field. It is called by the builders before save.
	comments.IDValidator = commentsDescID.Validators[0].(func(uint) error)
	objectsFields := schema.Objects{}.Fields()
	_ = objectsFields
	// objectsDescDescription is the schema descriptor for description field.
	objectsDescDescription := objectsFields[2].Descriptor()
	// objects.DefaultDescription holds the default value on creation for the description field.
	objects.DefaultDescription = objectsDescDescription.Default.(string)
	// objectsDescCoordinateX is the schema descriptor for coordinate_x field.
	objectsDescCoordinateX := objectsFields[3].Descriptor()
	// objects.CoordinateXValidator is a validator for the "coordinate_x" field. It is called by the builders before save.
	objects.CoordinateXValidator = objectsDescCoordinateX.Validators[0].(func(int) error)
	// objectsDescCoordinateY is the schema descriptor for coordinate_y field.
	objectsDescCoordinateY := objectsFields[4].Descriptor()
	// objects.CoordinateYValidator is a validator for the "coordinate_y" field. It is called by the builders before save.
	objects.CoordinateYValidator = objectsDescCoordinateY.Validators[0].(func(int) error)
	// objectsDescLength is the schema descriptor for length field.
	objectsDescLength := objectsFields[5].Descriptor()
	// objects.LengthValidator is a validator for the "length" field. It is called by the builders before save.
	objects.LengthValidator = objectsDescLength.Validators[0].(func(int) error)
	// objectsDescWidth is the schema descriptor for width field.
	objectsDescWidth := objectsFields[6].Descriptor()
	// objects.WidthValidator is a validator for the "width" field. It is called by the builders before save.
	objects.WidthValidator = objectsDescWidth.Validators[0].(func(int) error)
	// objectsDescOrder is the schema descriptor for order field.
	objectsDescOrder := objectsFields[7].Descriptor()
	// objects.OrderValidator is a validator for the "order" field. It is called by the builders before save.
	objects.OrderValidator = objectsDescOrder.Validators[0].(func(int) error)
	// objectsDescCreatedAt is the schema descriptor for created_at field.
	objectsDescCreatedAt := objectsFields[10].Descriptor()
	// objects.DefaultCreatedAt holds the default value on creation for the created_at field.
	objects.DefaultCreatedAt = objectsDescCreatedAt.Default.(func() time.Time)
	// objectsDescUpdatedAt is the schema descriptor for updated_at field.
	objectsDescUpdatedAt := objectsFields[11].Descriptor()
	// objects.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	objects.DefaultUpdatedAt = objectsDescUpdatedAt.Default.(func() time.Time)
	// objects.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	objects.UpdateDefaultUpdatedAt = objectsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// objectsDescTouchVector is the schema descriptor for touch_vector field.
	objectsDescTouchVector := objectsFields[13].Descriptor()
	// objects.DefaultTouchVector holds the default value on creation for the touch_vector field.
	objects.DefaultTouchVector = objectsDescTouchVector.Default.(string)
	// objectsDescMarkerName is the schema descriptor for marker_name field.
	objectsDescMarkerName := objectsFields[14].Descriptor()
	// objects.DefaultMarkerName holds the default value on creation for the marker_name field.
	objects.DefaultMarkerName = objectsDescMarkerName.Default.(string)
	// objectsDescTimePoint is the schema descriptor for time_point field.
	objectsDescTimePoint := objectsFields[15].Descriptor()
	// objects.DefaultTimePoint holds the default value on creation for the time_point field.
	objects.DefaultTimePoint = objectsDescTimePoint.Default.(float64)
	// objectsDescID is the schema descriptor for id field.
	objectsDescID := objectsFields[0].Descriptor()
	// objects.IDValidator is a validator for the "id" field. It is called by the builders before save.
	objects.IDValidator = objectsDescID.Validators[0].(func(uint) error)
	reactionsFields := schema.Reactions{}.Fields()
	_ = reactionsFields
	// reactionsDescDescription is the schema descriptor for description field.
	reactionsDescDescription := reactionsFields[2].Descriptor()
	// reactions.DefaultDescription holds the default value on creation for the description field.
	reactions.DefaultDescription = reactionsDescDescription.Default.(string)
	// reactionsDescName is the schema descriptor for name field.
	reactionsDescName := reactionsFields[3].Descriptor()
	// reactions.NameValidator is a validator for the "name" field. It is called by the builders before save.
	reactions.NameValidator = func() func(string) error {
		validators := reactionsDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// reactionsDescNumber is the schema descriptor for number field.
	reactionsDescNumber := reactionsFields[4].Descriptor()
	// reactions.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	reactions.NumberValidator = reactionsDescNumber.Validators[0].(func(int) error)
	// reactionsDescTimePoint is the schema descriptor for time_point field.
	reactionsDescTimePoint := reactionsFields[5].Descriptor()
	// reactions.TimePointValidator is a validator for the "time_point" field. It is called by the builders before save.
	reactions.TimePointValidator = reactionsDescTimePoint.Validators[0].(func(float64) error)
	// reactionsDescCreatedAt is the schema descriptor for created_at field.
	reactionsDescCreatedAt := reactionsFields[6].Descriptor()
	// reactions.DefaultCreatedAt holds the default value on creation for the created_at field.
	reactions.DefaultCreatedAt = reactionsDescCreatedAt.Default.(func() time.Time)
	// reactionsDescUpdatedAt is the schema descriptor for updated_at field.
	reactionsDescUpdatedAt := reactionsFields[7].Descriptor()
	// reactions.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	reactions.DefaultUpdatedAt = reactionsDescUpdatedAt.Default.(func() time.Time)
	// reactions.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	reactions.UpdateDefaultUpdatedAt = reactionsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// reactionsDescID is the schema descriptor for id field.
	reactionsDescID := reactionsFields[0].Descriptor()
	// reactions.IDValidator is a validator for the "id" field. It is called by the builders before save.
	reactions.IDValidator = reactionsDescID.Validators[0].(func(uint) error)
	videosFields := schema.Videos{}.Fields()
	_ = videosFields
	// videosDescDescription is the schema descriptor for description field.
	videosDescDescription := videosFields[2].Descriptor()
	// videos.DefaultDescription holds the default value on creation for the description field.
	videos.DefaultDescription = videosDescDescription.Default.(string)
	// videosDescVersion is the schema descriptor for version field.
	videosDescVersion := videosFields[10].Descriptor()
	// videos.DefaultVersion holds the default value on creation for the version field.
	videos.DefaultVersion = videosDescVersion.Default.(uint)
	// videosDescCreatedAt is the schema descriptor for created_at field.
	videosDescCreatedAt := videosFields[12].Descriptor()
	// videos.DefaultCreatedAt holds the default value on creation for the created_at field.
	videos.DefaultCreatedAt = videosDescCreatedAt.Default.(func() time.Time)
	// videosDescUpdatedAt is the schema descriptor for updated_at field.
	videosDescUpdatedAt := videosFields[13].Descriptor()
	// videos.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	videos.DefaultUpdatedAt = videosDescUpdatedAt.Default.(func() time.Time)
	// videos.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	videos.UpdateDefaultUpdatedAt = videosDescUpdatedAt.UpdateDefault.(func() time.Time)
	viewersFields := schema.Viewers{}.Fields()
	_ = viewersFields
	// viewersDescVideoID is the schema descriptor for video_id field.
	viewersDescVideoID := viewersFields[1].Descriptor()
	// viewers.VideoIDValidator is a validator for the "video_id" field. It is called by the builders before save.
	viewers.VideoIDValidator = viewersDescVideoID.Validators[0].(func(uint) error)
	// viewersDescNumber is the schema descriptor for number field.
	viewersDescNumber := viewersFields[2].Descriptor()
	// viewers.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	viewers.NumberValidator = viewersDescNumber.Validators[0].(func(int) error)
	// viewersDescTimePoint is the schema descriptor for time_point field.
	viewersDescTimePoint := viewersFields[3].Descriptor()
	// viewers.TimePointValidator is a validator for the "time_point" field. It is called by the builders before save.
	viewers.TimePointValidator = viewersDescTimePoint.Validators[0].(func(float64) error)
	// viewersDescCreatedAt is the schema descriptor for created_at field.
	viewersDescCreatedAt := viewersFields[4].Descriptor()
	// viewers.DefaultCreatedAt holds the default value on creation for the created_at field.
	viewers.DefaultCreatedAt = viewersDescCreatedAt.Default.(func() time.Time)
	// viewersDescUpdatedAt is the schema descriptor for updated_at field.
	viewersDescUpdatedAt := viewersFields[5].Descriptor()
	// viewers.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	viewers.DefaultUpdatedAt = viewersDescUpdatedAt.Default.(func() time.Time)
	// viewers.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	viewers.UpdateDefaultUpdatedAt = viewersDescUpdatedAt.UpdateDefault.(func() time.Time)
	// viewersDescID is the schema descriptor for id field.
	viewersDescID := viewersFields[0].Descriptor()
	// viewers.IDValidator is a validator for the "id" field. It is called by the builders before save.
	viewers.IDValidator = viewersDescID.Validators[0].(func(uint) error)
}
