// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comments is the predicate function for comments builders.
type Comments func(*sql.Selector)

// Objects is the predicate function for objects builders.
type Objects func(*sql.Selector)

// Reactions is the predicate function for reactions builders.
type Reactions func(*sql.Selector)

// Videos is the predicate function for videos builders.
type Videos func(*sql.Selector)

// Viewers is the predicate function for viewers builders.
type Viewers func(*sql.Selector)
